# Generated by Django 2.2.4 on 2019-08-28 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('corporate_id', models.SmallIntegerField()),
                ('login_name', models.CharField(max_length=20)),
                ('login_pass', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SylectusUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='checker_kpi.Companys')),
            ],
        ),
        migrations.CreateModel(
            name='OperationsUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(max_length=40)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='checker_kpi.Companys')),
            ],
        ),
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=40)),
                ('creds', models.BinaryField(default=b'')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='checker_kpi.Companys')),
            ],
        ),
    ]
