# Generated by Django 2.2.4 on 2019-08-28 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checker_kpi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Companys',
            new_name='Company',
        ),
    ]
