# Generated by Django 2.2.4 on 2019-09-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker_kpi', '0003_auto_20190829_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='emails',
            name='check_for_this_email',
            field=models.BooleanField(default=True),
        ),
    ]
