# Generated by Django 2.2.3 on 2019-09-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker_kpi', '0004_emails_check_for_this_email'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='emails',
            name='uniq user',
        ),
        migrations.AlterField(
            model_name='emails',
            name='creds',
            field=models.BinaryField(default=b'', max_length=500),
        ),
        migrations.AddConstraint(
            model_name='emails',
            constraint=models.UniqueConstraint(fields=('company', 'email', 'check_for_this_email', 'creds'), name='uniq user'),
        ),
    ]
