# Generated by Django 2.2.3 on 2019-09-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker_kpi', '0005_auto_20190903_0615'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='emails',
            name='uniq user',
        ),
        migrations.AlterField(
            model_name='emails',
            name='email',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AddConstraint(
            model_name='emails',
            constraint=models.UniqueConstraint(fields=('company', 'email'), name='uniq user'),
        ),
    ]
