# Generated by Django 2.2.4 on 2019-09-26 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checker_kpi', '0006_auto_20190903_0629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emails',
            name='creds',
        ),
    ]
