# Generated by Django 2.2.4 on 2019-11-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker_kpi', '0007_remove_emails_creds'),
    ]

    operations = [
        migrations.AddField(
            model_name='emails',
            name='refresh_token',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='emails',
            name='token',
            field=models.CharField(default='', max_length=70),
        ),
    ]
